openapi: 3.0.0
info:
  title: デジタルスタンプラリーシステム API
  description: LINE公式アカウントと連携したデジタルスタンプラリーシステムのバックエンドAPI仕様
  version: 1.0.0

servers:
  - url: https://{region}-{projectId}.cloudfunctions.net
    variables:
      region:
        default: asia-northeast1
        description: Cloud Functionsのリージョン
      projectId:
        default: your-project-id
        description: FirebaseプロジェクトID

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    LineSignature:
      type: apiKey
      in: header
      name: X-Line-Signature
      description: LINE Webhookの署名検証用

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

    Stamp:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        storeId:
          type: string
        timestamp:
          type: string
          format: date-time

    ExportStatus:
      type: object
      properties:
        jobId:
          type: string
        status:
          type: string
          enum: [pending, processing, completed, failed]
        progress:
          type: number
          minimum: 0
          maximum: 100
        result:
          type: object
          properties:
            spreadsheetUrl:
              type: string
            error:
              type: string

paths:
  /api/stamps:
    post:
      summary: スタンプの付与
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - storeId
                - qrCode
              properties:
                storeId:
                  type: string
                qrCode:
                  type: string
      responses:
        '200':
          description: スタンプ付与成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stamp'
        '400':
          description: 無効なリクエスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: 認証エラー
        '403':
          description: 権限エラー

  /api/webhook:
    post:
      summary: LINE Webhook受信
      security:
        - LineSignature: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                events:
                  type: array
                  items:
                    type: object
      responses:
        '200':
          description: Webhook処理成功
        '400':
          description: 無効なリクエスト
        '401':
          description: 署名検証エラー

  /api/admin/users:
    get:
      summary: ユーザー一覧取得
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: ユーザー一覧取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
        '401':
          description: 認証エラー
        '403':
          description: 権限エラー

  /api/analytics:
    get:
      summary: 分析データ取得
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: startDate
          schema:
            type: string
            format: date
        - in: query
          name: endDate
          schema:
            type: string
            format: date
      responses:
        '200':
          description: 分析データ取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalUsers:
                    type: integer
                  activeUsers:
                    type: integer
                  totalStamps:
                    type: integer
                  storeStats:
                    type: array
                    items:
                      type: object
        '401':
          description: 認証エラー
        '403':
          description: 権限エラー

  /api/export/spreadsheet:
    post:
      summary: スプレッドシート書き出し開始
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - startDate
                - endDate
              properties:
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
                includeFields:
                  type: array
                  items:
                    type: string
      responses:
        '202':
          description: 書き出しジョブ開始
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    type: string
        '401':
          description: 認証エラー
        '403':
          description: 権限エラー

  /api/export/status/{jobId}:
    get:
      summary: 書き出し状況確認
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: jobId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 書き出し状況取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportStatus'
        '401':
          description: 認証エラー
        '403':
          description: 権限エラー
        '404':
          description: ジョブが見つかりません